version: '3.7'
services:
  php:
    container_name: simple-blog.local-prod
    image: 'defaultvalue/php:8.1-production'
    user: 'docker:docker'
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.simple-blog-local-http.rule=Host(`simple-blog.local`,`www.simple-blog.local`)'
      - traefik.http.routers.simple-blog-local-http.entrypoints=http
      - traefik.http.routers.simple-blog-local-http.service=simple-blog-local-http
      - traefik.http.services.simple-blog-local-http.loadbalancer.server.port=80
      - traefik.http.services.simple-blog-local-http.loadbalancer.server.scheme=http
      - 'traefik.http.routers.simple-blog-local-https.rule=Host(`simple-blog.local`,`www.simple-blog.local`)'
      - traefik.http.routers.simple-blog-local-https.entrypoints=https
      - traefik.http.routers.simple-blog-local-https.tls=true
      - traefik.http.routers.simple-blog-local-https.service=simple-blog-local-https
      - traefik.http.services.simple-blog-local-https.loadbalancer.server.port=443
      - traefik.http.services.simple-blog-local-https.loadbalancer.server.scheme=https
    extra_hosts:
      - 'simple-blog.local www.simple-blog.local:127.0.0.1'
    environment:
      - COMPOSER_VERSION=2
    volumes:
      - '../../:/var/www/html'
      - '${SSL_CERTIFICATES_DIR}:/certs'
      - './apache/virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
