version: '3.7'
services:
  php:
    image: 'defaultvalue/php:8.1-development'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - ADDITIONAL_PATH=/usr/local/go/bin
      - PHP_IDE_CONFIG=serverName=simple-blog.local
      - COMPOSER_VERSION=2
  mailhog:
    image: 'mailhog/mailhog:v1.0.1'
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mh-prod-simple-blog-local-http.rule=Host(`mh-prod-simple-blog.local`)
      - traefik.http.routers.mh-prod-simple-blog-local-http.entrypoints=http
      - traefik.http.services.mh-prod-simple-blog-local-http.loadbalancer.server.port=8025
